### ISSUE TITLE
from jitar-0.0.4 to jitar-0.3.3

### ISSUE THREAD

**Issue by wannaphong** [danieldk/jitar#4]
I use jitar-0.0.4 for many years. Now , I want to using jitar-0.3.3 but It error.

> java -cp jitar-0.0.4.jar org.langkit.tagger.cli.Tag lexicon ngrams < test.txt

Can you suggest anything?
Thank you for jitar development.

**Comment by danieldk** [comment]
What error do you get?

Also note that newer versions of Jitar use a Java serialized class as the model, not separate lexicon and ngram files. Did you try to just retrain the model to get a model in the new format?

**Comment by wannaphong** [comment]
Yes, I try to just retrain the model but  tag model not working.
```
C:\jitar_model_large\jitar_model_large>java -cp jitar-0.3.3.jar eu.danieldk.nlp.jitar.cli.Train brown lexicon ngrams newlang.model
Train [brown/conll] corpus model

C:\jitar_model_large\jitar_model_large>java -cp jitar-0.3.3.jar eu.danieldk.nlp.jitar.cli.Tag "The cat is on the mat ." newlang.model
tag model

C:\jitar_model_large\jitar_model_large>
```

**Comment by danieldk** [comment]
The output shown is usage information (maybe it should be more explicit about that). If your corpus is named `mycorpus` and is in the Brown format, you can train as follows:

~~~
java -cp jitar-0.3.3.jar eu.danieldk.nlp.jitar.cli.Train brown mycorpus mymodel
~~~

This will write the file `mymodel`. You can then tag using:

~~~
java -cp jitar-0.3.3.jar eu.danieldk.nlp.jitar.cli.Tag mymodel
~~~

(Which reads from the standard input.)

**Comment by wannaphong** [comment]
My corpus isn't in the Brown format. https://gist.github.com/wannaphongcom/c555961ca4736bcd2eadf42635672ddf

**Comment by danieldk** [comment]
That's a trained model, not a corpus. You will have to retrain the tagger on the original corpus. Besides the changed model format, there were some changes in the treatment of tags (a capitalization marker is stored in the tags), so a 0.0.4 model will not work as-is.

**Comment by wannaphong** [comment]
Original corpus has been lost. I would need to use jitar-0.0.4.
If I want to create a new corpus. Can you suggest how to create a corpus like Brown?

**Comment by danieldk** [comment]
The format is simple:

* Tokens are separated by a space.
* Sentences are separated by newlines.
* Part-of-speech tags are attached to tokens using a forward slash (e.g. *man/NN*).

Note that Jitar also supports the CoNLL-X format, which may be more convenient:

http://web.archive.org/web/20160814191537/http://ilk.uvt.nl/conll

**Comment by wannaphong** [comment]
Thank you very much.
